$schema: "$schema: http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
contentVersion: "1.0.0.0"
parameters: {}
variables:
  location: "[resourceGroup().location]"
  apiVersion: "2015-06-15"
  # adminUserName: "[parameters('adminUserName')]"
  # adminPassword: "[parameters('adminPassword')]"
  newStorageAccountName: "[concat('storage', uniqueString(resourceGroup().id))]"
  storageAccountType: Standard_LRS
resources:
    - type: "Microsoft.Storage/storageAccounts"
      name: "[variables('newStorageAccountName')]"
      apiVersion: "[variables('apiVersion')]"
      location: "[variables('location')]"
      properties:
        accountType: "[variables('storageAccountType')]"
outputs: {}
